In [15]:
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    ' I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 ' I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [17]:
## Define vocabulary size
voc_size=10000

In [18]:
## One hot Representation

one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3130, 676, 922, 2895],
 [3130, 676, 922, 4728],
 [3130, 1064, 922, 5294],
 [1399, 5346, 6665, 5072, 7846],
 [1399, 5346, 6665, 5072, 4206],
 [9664, 3130, 4408, 922, 3182],
 [5319, 2672, 4186, 5072]]

In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [20]:
import numpy as np
import pandas as pd

In [21]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3130  676  922 2895]
 [   0    0    0    0 3130  676  922 4728]
 [   0    0    0    0 3130 1064  922 5294]
 [   0    0    0 1399 5346 6665 5072 7846]
 [   0    0    0 1399 5346 6665 5072 4206]
 [   0    0    0 9664 3130 4408  922 3182]
 [   0    0    0    0 5319 2672 4186 5072]]


In [22]:
## Feature representation
dim=10

In [23]:
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\ACER\Desktop\data analytics\python\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[-0.0161521 , -0.03938818,  0.04700163,  0.04331532,
          0.04790267,  0.01661799, -0.00344036, -0.00571549,
         -0.00869452,  0.00489259],
        [-0.0161521 , -0.03938818,  0.04700163,  0.04331532,
          0.04790267,  0.01661799, -0.00344036, -0.00571549,
         -0.00869452,  0.00489259],
        [-0.0161521 , -0.03938818,  0.04700163,  0.04331532,
          0.04790267,  0.01661799, -0.00344036, -0.00571549,
         -0.00869452,  0.00489259],
        [-0.0161521 , -0.03938818,  0.04700163,  0.04331532,
          0.04790267,  0.01661799, -0.00344036, -0.00571549,
         -0.00869452,  0.00489259],
        [-0.03798838,  0.01755286,  0.01646395, -0.01677197,
          0.04567614, -0.0294733 , -0.03770278, -0.01806978,
          0.02761432, -0.02984307],
        [ 0.03310532, -0.01011954,  0.03906795, -0.03102559,
          0.02471831, -0.0039255 , -0.04295398,  0.03055731,
          0.04945215,  0.02102201],
        [ 0.00968011, -0.00662465,  0.02545131,  0.0

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 3130,  676,  922, 2895], dtype=int32)

In [26]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[ 0.02941983, -0.01225152, -0.0179399 , -0.01745061,  0.02203873,
         0.03605456, -0.01737954,  0.01652903,  0.04154769,  0.02774997],
       [ 0.02941983, -0.01225152, -0.0179399 , -0.01745061,  0.02203873,
         0.03605456, -0.01737954,  0.01652903,  0.04154769,  0.02774997],
       [ 0.02941983, -0.01225152, -0.0179399 , -0.01745061,  0.02203873,
         0.03605456, -0.01737954,  0.01652903,  0.04154769,  0.02774997],
       [ 0.02941983, -0.01225152, -0.0179399 , -0.01745061,  0.02203873,
         0.03605456, -0.01737954,  0.01652903,  0.04154769,  0.02774997],
       [-0.01322954, -0.03351456, -0.0297114 ,  0.04565204,  0.0423176 ,
        -0.00501787,  0.03657596, -0.02204247, -0.00708605,  0.0004651 ],
       [ 0.023585  , -0.02382123, -0.02818047,  0.00256325,  0.01743444,
        -0.00866456,  0.00860874, -0.03094512, -0.02117829,  0.0368714 ],
       [ 0.0445698 , -0.04058998, -0.04167316,  0.03937335, -0.01211346,
        -0.04348842,  0.04922571, -0.04017826